[package]
name = "semver-jni-rs"
version = "0.1.0"
authors = ["Joseph Hejderup <jhejderup@users.noreply.github.com>"]
edition = "2018"


[lib]
crate_type = ["cdylib"]

[dependencies]
jni = "0.11.0"
semver = "0.9.0"